# Header
menu:
  home: /
  文章: /articles/ || newspaper
  相册: /photos/ || images
  标签: /tags/ || tags

rss: /atom.xml
github: https://github.com/myname
logo_title: 
blog_title: 这才是我的世界

# Content
# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false


# Sidebar
sidebar: right
widgets:
- recent_posts
- tag
- archive

# Miscellaneous
wx_block: false
google_analytics:
favicon:
twitter:
google_plus:
fb_admins:
fb_app_id:

# Duoshuo
duoshuo_shortname:

# Swiftype Search
swiftype_key: