# Header
menu:
  主页: /
  文章: /archives
  相册: /about
rss: /atom.xml
github: https://github.com/myname
logo_title: 
blog_title: 这才是我的世界

# Content
excerpt_link: Read More
fancybox: true
mathjax: false

# Sidebar
sidebar: right
widgets:
- recent_posts
- tag
- archive

# Miscellaneous
wx_block: false
google_analytics:
favicon:
twitter:
google_plus:
fb_admins:
fb_app_id:

# Duoshuo
duoshuo_shortname:

# Swiftype Search
swiftype_key: